package com.gpsso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-06-05T16:35:17.922+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://gpsso.com/", name = "IdCardSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IdCardSoap {

    /**
     * 身份证号码查询，请输入15位或18位身份证
     */
    @WebMethod(operationName = "SearchIdCard", action = "http://gpsso.com/SearchIdCard")
    @RequestWrapper(localName = "SearchIdCard", targetNamespace = "http://gpsso.com/", className = "com.gpsso.SearchIdCard")
    @ResponseWrapper(localName = "SearchIdCardResponse", targetNamespace = "http://gpsso.com/", className = "com.gpsso.SearchIdCardResponse")
    @WebResult(name = "SearchIdCardResult", targetNamespace = "http://gpsso.com/")
    public com.gpsso.SearchIdCardResponse.SearchIdCardResult searchIdCard(
        @WebParam(name = "IdCard", targetNamespace = "http://gpsso.com/")
        java.lang.String idCard
    );
}
