package com.gpsso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2015-06-05T16:35:18.009+08:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://gpsso.com/", name = "IdCardHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IdCardHttpGet {

    /**
     * 身份证号码查询，请输入15位或18位身份证
     */
    @WebMethod(operationName = "SearchIdCard")
    @WebResult(name = "Body", targetNamespace = "", partName = "Body")
    public java.lang.String searchIdCard(
        @WebParam(partName = "IdCard", name = "IdCard", targetNamespace = "")
        java.lang.String idCard
    );
}
